services: 
  - type: web 
    runtime: node
    name: my-service
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydatabase
          property: connectionString

databases:
  - name: pstgres-db
    user: esgi
    
